version: '3.1'
services:
  imap-server:
    image: greenmail/standalone:2.1.0-rc-1
    ports:
      - 3143:3143
      - 3993:3993
      - 8080:8080
    environment:
      GREENMAIL_OPTS: '
        -Dgreenmail.setup.test.imap
        -Dgreenmail.setup.test.imaps
        -Dgreenmail.hostname=0.0.0.0 
        -Dgreenmail.users=user:pass@localhost
        -Dgreenmail.verbose
        '